version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./app:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"